{
 "title": "Custom Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Users logged in last hour",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "auth0{auth0=\"amount_of_users_logged_in_last_hour\"}"
    }
   ]
  },
  {
   "title": "Amount of Users",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "auth0{auth0=\"amount_of_users\"}"
    }
   ]
  },
  {
   "title": "Amount of Users (non polylith)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "auth0{auth0=\"get_amount_of_non_polylith_users\"}"
    }
   ]
  }
 ]
}